version: '3.4'

services:
  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    volumes:
      - postgres_data:/var/lib/postgressql/data/
  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
  catalogdb:
    container_name: catalogdb
    restart: always
    volumes:
    - mongo_data:/data/db
    ports:
      - 27017:27017
  catalog.api:
    container_name: catalog.api
    ports:
    - 8000:80
    environment:
    -  ASPNETCORE_ENVIRONMENT=Development
    - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017" 
    - "DatabaseSettings:DatabaseName=ProductDb" 
    - "DatabaseSettings:CollectionName=Products" 
    depends_on:
    - catalogdb
  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;TrustServerCertificate=true;" 
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672" 
    depends_on:
        - orderdb
        - rabbitmq
    ports:
        - "8004:80"
  rediscache:
    container_name: rediscache
    restart: always
    #volumes:
    #- redis_data:/data #We are not going to store  in volume as it is distributed cache
    ports:
      - 6379:6379
  basket.api:
    container_name: basket.api
    ports:
    - 8001:80
    environment:
    -  ASPNETCORE_ENVIRONMENT=Development
    - "CacheSettings:ConnectionString=rediscache:6379" 
    - "GrpcSettings:DiscountUrl=http://discount.grpc" 
    - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
    - rediscache    
    - rabbitmq
  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234"
    ports:
      - "8003:80"
    depends_on:
      - discountdb
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672" 
        - "15672:15672" #for portal access

  shopping.aggregator:
   container_name: shopping.aggregator
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - "ApiSettings:CatalogUrl=http://catalog.api:80"
     - "ApiSettings:BasketUrl=http://basket.api:80"
     - "ApiSettings:OrderingUrl=http://ordering.api:80"
   ports:
     - "8006:80"
   depends_on:
        - catalog.api
        - basket.api
        - discount.grpc
        - ordering.api

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - catalog.api
        - basket.api
        - discount.grpc
        - ordering.api
    ports:
      - "8010:80"
        

  aspnetrunbasics:
    container_name: aspnetrunbasics
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:GatewayAddress=http://ocelotapigw"
    depends_on:
      - ocelotapigw
      - catalog.api
      - basket.api
      - discount.grpc
      - ordering.api
    ports:
      - "8007:80"