version: '3.4'

services:
  catalogdb:
    image: mongo
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  rediscache:
    image: redis:alpine
  basket.api:
    image:  ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  portainer:
    image: portainer/portainer-ce
volumes:
   mongo_data:
   redis_data:
   portainer_data: 