version: '3.4'

services:
  discountdb:
    image: postgres
  catalogdb:
    image: mongo
  rediscache:
    image: redis:alpine
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  basket.api:
    image:  ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Discount.Grpc/Dockerfile

volumes:
   mongo_data:
   redis_data:
   postgres_data: 
