version: '3.4'

services:
  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    volumes:
      - postgres_data:/var/lib/postgressql/data/
  catalogdb:
    container_name: catalogdb
    restart: always
    volumes:
    - mongo_data:/data/db
    ports:
      - 27017:27017
  catalog.api:
    container_name: catalog.api
    ports:
    - 8900:80
    environment:
    -  ASPNETCORE_ENVIRONMENT=Development
    - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017" 
    - "DatabaseSettings:DatabaseName=ProductDb" 
    - "DatabaseSettings:CollectionName=Products" 
    depends_on:
    - catalogdb
  rediscache:
    container_name: rediscache
    restart: always
    #volumes:
    #- redis_data:/data #We are not going to store  in volume as it is distributed cache
    ports:
      - 6379:6379
  basket.api:
    container_name: basket.api
    ports:
    - 9000:80
    environment:
    -  ASPNETCORE_ENVIRONMENT=Development
    - "CacheSettings:ConnectionString=rediscache:6379" 
    depends_on:
    - rediscache
  discount.api:
    container_name: discount.api
    ports:
    - 5000:80
    environment:
    -  ASPNETCORE_ENVIRONMENT=Development
    -  "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234"
    depends_on:
    - discountdb
    